import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-rows-[1fr,auto] items-center p-5 font-[family-name:var(--font-geist-sans)]">
          <header className="flex flex-col items-start gap-4 ">
            <Link href="/">
              <Image
                src="/shape_logo_black.svg"
                alt="Shape Logo"
                width={100}
                height={100}
              />
            </Link>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
